### ISSUE TITLE
[Bug]: Build job failed to close GitHub issue because on null object.

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build-libraries#372]
### Describe the bug

The post stage of our distribution build job failed on closing GitHub issue because it pointed on null object.
https://github.com/opensearch-project/opensearch-build-libraries/blob/ae6bcadce1b06f8d9ef365748c417e8e77e42b96/vars/closeBuildSuccessGithubIssue.groovy#L20
The job ends up marking as failed even though all build and assemble are succeed and all artifacts are uploaded. 
More context:
```
Error when executing always post condition:
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 4bfa0068-7d2e-4716-bb0f-27d9c83d6f4c
java.lang.NullPointerException: Cannot invoke method unique() on null object
```
https://build.ci.opensearch.org/job/distribution-build-opensearch-dashboards/7164/console

### To reproduce

Run distribution build job.

**Comment by rishabh6788** [comment]
Seems like the issue is fixed as we have successful OSD builds https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/7295/pipeline

See https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/UpdateBuildFailureIssues.groovy#L31-L35
