### ISSUE TITLE
[PROPOSAL]  Add tests for groovy scripts in vars folder

### ISSUE THREAD

**Issue by pranav767** [opensearch-project/opensearch-build-libraries#508]
### Is your feature request related to a problem? Please describe

Currently from build.gradle we can see that the tests are only covering `'src/jenkins', 'src/gradlecheck'`  . I can see multiple groovy scripts inside `vars` directory which are not yet covered in the unit tests.
Correct me if I am wrong, but I feel this scripts are as important as the others in the src directory.
I do see there are tests written in jobs directory,but these seem to be more like integration/regression tests than unit tests

### Describe the solution you'd like

We could start writing tests for each groovy files in `vars` directory, and add the sourcefile in build.gradle , while maintaining the record of which groovy scripts are covered and which needs to be covered yet.

**Comment by gaiksaya** [comment]
Hi @pranav767 

Thank you for opening the issue. We are using [JenkinsPipelineUnit](https://github.com/jenkinsci/JenkinsPipelineUnit) for testing the libraries in `vars` folder. See the developer guide for more details. https://github.com/opensearch-project/opensearch-build-libraries/blob/main/DEVELOPER_GUIDE.md#run-tests

Are you suggesting anything else other than these? Please feel to contribute as well so that we get more idea.

Thanks!

**Comment by pranav767** [comment]
Hey @gaiksaya ,thank you for your response 
Apologies, after reading https://github.com/opensearch-project/opensearch-build-libraries/blob/main/DEVELOPER_GUIDE.md#run-tests
I could see that tests are well written 👏
